services:
  votist:
    build:
      dockerfile: Dockerfile
    container_name: votist
    ports:
      - '5173:5173'
    environment:
      - DATABASE_URL=postgresql://votist_user:votist_password@db:5432/votist_db
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.svelte-kit
      - /app/prisma/generated
      - /app/node_modules/@prisma-generated
    command: npm run dev -- --host
    depends_on:
      - db

  db:
    container_name: votist_db
    image: postgres:15
    environment:
      - POSTGRES_DB=votist_db
      - POSTGRES_USER=votist_user
      - POSTGRES_PASSWORD=votist_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
